events {
    worker_connections 1024;
}

http {
    upstream backend_api {
        # Docker's built-in DNS will resolve this to the IP addresses of all replicas
        server backend-api:3001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
